# Generated by Django 4.1.7 on 2023-04-08 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news_portal', '0002_alter_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_time_in',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_time_in',
            new_name='date_creation',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='post_category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='post_title',
        ),
        migrations.RemoveField(
            model_name='author',
            name='user_rating',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type',
        ),
        migrations.AddField(
            model_name='author',
            name='author_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=3.9, max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('AR', 'статья'), ('NW', 'новость')], default='NW', max_length=2),
        ),
        migrations.AlterField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='news_portal.author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.IntegerField(default=0),
        ),
    ]
